UPDATE public.reader_sources
SET enabled = FALSE
WHERE feed_url IN (
  'https://www.money.pl/rss/rss-gospodarka.xml',
  'https://stooq.pl/rss/',
  'https://www.stockwatch.pl/rss/'
);

INSERT INTO public.reader_sources (name, category, feed_url, priority, enabled)
VALUES
  ('Bankier Wiadomości', 'Polska / Gospodarka / Giełda', 'https://www.bankier.pl/rss/wiadomosci.xml', 4, TRUE),
  ('Bankier Giełda', 'Polska / Giełda', 'https://www.bankier.pl/rss/gielda.xml', 4, TRUE),
  ('Deutsche Welle World', 'Świat / Geopolityka / Europa', 'https://rss.dw.com/rdf/rss-en-world', 4, TRUE),
  ('France 24 English', 'Świat / Geopolityka', 'https://www.france24.com/en/rss', 4, TRUE),
  ('UN News', 'Świat / Geopolityka / Organizacje', 'https://news.un.org/feed/subscribe/en/news/all/rss.xml', 3, TRUE),
  ('EU Commission Press Corner', 'Świat / Geopolityka / Europa', 'https://ec.europa.eu/commission/presscorner/api/rss?language=en', 3, TRUE),
  ('Deutsche Welle Business', 'Świat / Biznes / Europa', 'https://rss.dw.com/rdf/rss-en-bus', 3, TRUE),
  ('SEC Press Releases', 'Świat / Biznes / Regulator', 'https://www.sec.gov/news/pressreleases.rss', 3, TRUE),
  ('Federal Reserve Press Releases', 'Świat / Biznes / Bank centralny', 'https://www.federalreserve.gov/feeds/press_all.xml', 4, TRUE),
  ('ECB Press', 'Świat / Biznes / Bank centralny', 'https://www.ecb.europa.eu/rss/press.html', 4, TRUE),
  ('EIA Today in Energy', 'Świat / Biznes / Energy', 'https://www.eia.gov/rss/todayinenergy.xml', 3, TRUE),
  ('Cloudflare Blog', 'Software / Infrastructure', 'https://blog.cloudflare.com/rss/', 4, TRUE),
  ('Kubernetes Blog', 'Software / Infrastructure', 'https://kubernetes.io/feed.xml', 3, TRUE),
  ('AWS News Blog', 'Software / Cloud', 'https://aws.amazon.com/blogs/aws/feed/', 3, TRUE),
  ('Microsoft Azure Blog', 'Software / Cloud', 'https://azure.microsoft.com/en-us/blog/feed/', 3, TRUE),
  ('Rust Blog', 'Software / Languages', 'https://blog.rust-lang.org/feed.xml', 3, TRUE),
  ('Go Blog', 'Software / Languages', 'https://go.dev/blog/feed.atom', 3, TRUE),
  ('Node.js Blog', 'Software / Languages', 'https://nodejs.org/en/feed/blog.xml', 3, TRUE),
  ('OpenAI News', 'AI / Labs', 'https://openai.com/news/rss.xml', 5, TRUE),
  ('Google DeepMind Blog', 'AI / Labs', 'https://deepmind.google/blog/rss.xml', 5, TRUE),
  ('Google AI Blog', 'AI / Labs', 'https://blog.google/technology/ai/rss/', 4, TRUE),
  ('Google Research Blog', 'AI / Research', 'https://research.google/blog/rss/', 4, TRUE),
  ('NVIDIA Blog - AI', 'AI / Hardware / Rynek', 'https://blogs.nvidia.com/blog/category/deep-learning/feed/', 4, TRUE),
  ('Import AI', 'AI / Policy / Research', 'https://jack-clark.net/feed/', 3, TRUE),
  ('TechCrunch AI', 'AI / Biznes / Rynek', 'https://techcrunch.com/category/artificial-intelligence/feed/', 3, TRUE),
  ('MIT Technology Review AI', 'AI / Research / Rynek', 'https://www.technologyreview.com/topic/artificial-intelligence/feed', 3, TRUE),
  ('The Hacker News', 'Cybersecurity Global', 'https://feeds.feedburner.com/TheHackersNews', 2, TRUE),
  ('KrebsOnSecurity', 'Cybersecurity Global', 'https://krebsonsecurity.com/feed/', 2, TRUE),
  ('CISA Cybersecurity Advisories', 'Security / Official', 'https://www.cisa.gov/cybersecurity-advisories/all.xml', 1, TRUE),
  ('CISA Current Activity', 'Security / Official', 'https://www.cisa.gov/uscert/ncas/current-activity.xml', 1, TRUE),
  ('Google Online Security Blog', 'Security / Vendor Research', 'https://security.googleblog.com/feeds/posts/default', 2, TRUE),
  ('Microsoft Security Blog', 'Security / Vendor Research', 'https://www.microsoft.com/en-us/security/blog/feed/', 2, TRUE),
  ('Unit 42', 'Security / Threat Intelligence', 'https://unit42.paloaltonetworks.com/feed/', 2, TRUE),
  ('Cisco Talos Blog', 'Security / Threat Intelligence', 'https://blog.talosintelligence.com/rss/', 2, TRUE),
  ('Google Project Zero', 'Security / Vulnerability Research', 'https://googleprojectzero.blogspot.com/feeds/posts/default', 2, TRUE),
  ('SANS ISC Diary', 'Security / Incident Response', 'https://isc.sans.edu/rssfeed_full.xml', 2, TRUE),
  ('NCSC UK Guidance', 'Security / Official', 'https://www.ncsc.gov.uk/api/1/services/v1/all-rss-feed.xml', 2, TRUE),
  ('SecurityWeek', 'Cybersecurity Global', 'https://www.securityweek.com/feed/', 2, TRUE),
  ('Hacker News Newest', 'Software / IT', 'https://hnrss.org/newest', 2, FALSE),
  ('Lobsters', 'Software / IT', 'https://lobste.rs/rss', 3, FALSE),
  ('Simon Willison', 'Software / AI Engineering', 'https://simonwillison.net/atom/everything/', 3, FALSE),
  ('LWN.net', 'Software / Linux', 'https://lwn.net/headlines/rss', 3, FALSE),
  ('AWS What''s New', 'Software / Cloud', 'https://aws.amazon.com/about-aws/whats-new/recent/feed/', 2, FALSE),
  ('Cloudflare Changelog', 'Software / Infrastructure', 'https://developers.cloudflare.com/changelog/rss.xml', 2, FALSE),
  ('Mozilla Hacks', 'Software / Web', 'https://hacks.mozilla.org/feed/', 3, FALSE),
  ('Docker Blog', 'Software / Infrastructure', 'https://www.docker.com/blog/feed/', 3, FALSE),
  ('HashiCorp Blog', 'Software / Infrastructure', 'https://www.hashicorp.com/blog/feed.xml', 3, FALSE),
  ('SEC EDGAR Current Filings', 'Świat / Biznes / Markets', 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&output=atom', 2, FALSE),
  ('SEC EDGAR Recent 10-K', 'Świat / Biznes / Markets', 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=10-k&owner=include&count=40&output=atom', 2, FALSE),
  ('SEC EDGAR Recent 8-K', 'Świat / Biznes / Markets', 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=8-k&owner=include&count=40&output=atom', 2, FALSE),
  ('Federal Reserve Speeches', 'Świat / Biznes / Bank centralny', 'https://www.federalreserve.gov/feeds/speeches.xml', 2, FALSE),
  ('Federal Reserve H.15 Rates', 'Świat / Biznes / Markets', 'https://www.federalreserve.gov/feeds/h15.xml', 2, FALSE),
  ('ECB Blog', 'Świat / Biznes / Bank centralny', 'https://www.ecb.europa.eu/rss/blog.html', 2, FALSE),
  ('ECB Publications', 'Świat / Biznes / Bank centralny', 'https://www.ecb.europa.eu/rss/pub.html', 2, FALSE),
  ('France 24 Africa', 'Świat / Geopolityka / Afryka', 'https://www.france24.com/en/africa/rss', 2, FALSE),
  ('Deutsche Welle Top Stories', 'Świat / Geopolityka / Europa', 'https://rss.dw.com/xml/rss-en-all', 2, FALSE),
  ('The Verge AI', 'AI / Biznes / Rynek', 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml', 2, FALSE),
  ('Cybersecurity Dive', 'Cybersecurity Global', 'https://www.cybersecuritydive.com/feeds/news/', 2, FALSE),
  ('Dark Reading', 'Cybersecurity Global', 'https://www.darkreading.com/rss.xml', 2, FALSE),
  ('Risky Business News', 'Cybersecurity Global', 'https://news.risky.biz/rss/', 2, FALSE),
  ('Schneier on Security', 'Security / Analysis', 'https://www.schneier.com/feed/atom/', 2, FALSE),
  ('CISA News', 'Security / Official', 'https://www.cisa.gov/news.xml', 2, FALSE),
  ('NCSC UK News', 'Security / Official', 'https://www.ncsc.gov.uk/api/1/services/v1/news-rss-feed.xml', 2, FALSE),
  ('AWS Health Status', 'Software / Status', 'https://status.aws.amazon.com/rss/all.rss', 1, FALSE),
  ('Google Cloud Service Health', 'Software / Status', 'https://status.cloud.google.com/en/feed.atom', 1, FALSE),
  ('Cloudflare Status', 'Software / Status', 'https://www.cloudflarestatus.com/history.rss', 1, FALSE),
  ('GitHub Status', 'Software / Status', 'https://www.githubstatus.com/history.rss', 1, FALSE),
  ('OpenAI Status', 'Software / Status', 'https://status.openai.com/history.rss', 1, FALSE),
  ('Anthropic Status', 'Software / Status', 'https://status.anthropic.com/history.rss', 1, FALSE),
  ('Vercel Status', 'Software / Status', 'https://www.vercel-status.com/history.rss', 1, FALSE),
  ('WHO News', 'Świat / Geopolityka / Health', 'https://www.who.int/rss-feeds/news-english.xml', 2, FALSE),
  ('CDC Newsroom', 'Świat / Geopolityka / Health', 'https://tools.cdc.gov/api/v2/resources/media/132608.rss', 2, FALSE)
ON CONFLICT (feed_url) DO UPDATE
SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  priority = EXCLUDED.priority;
