INSERT INTO public.reader_sources (
  name,
  category,
  feed_url,
  priority,
  enabled,
  selection_mode,
  normalized_feed_url,
  canonical_host,
  feed_type,
  language,
  validation_status,
  last_validated_at,
  validation_diagnostics
)
VALUES
  ('ABC News International', 'Świat / Geopolityka / USA', 'https://feeds.abcnews.com/abcnews/internationalheadlines', 3, TRUE, 'always_on', 'https://feeds.abcnews.com/abcnews/internationalheadlines', 'feeds.abcnews.com', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('CBS News World', 'Świat / Geopolityka / USA', 'https://www.cbsnews.com/latest/rss/world', 3, TRUE, 'always_on', 'https://www.cbsnews.com/latest/rss/world', 'www.cbsnews.com', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('SBS News Latest', 'Świat / Geopolityka / Azja i Pacyfik', 'https://www.sbs.com.au/news/topic/latest/feed', 3, TRUE, 'always_on', 'https://www.sbs.com.au/news/topic/latest/feed', 'www.sbs.com.au', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('International Crisis Group', 'Świat / Geopolityka / Analizy i konflikty', 'https://www.crisisgroup.org/rss', 4, TRUE, 'always_on', 'https://www.crisisgroup.org/rss', 'www.crisisgroup.org', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('Africanews', 'Świat / Geopolityka / Afryka', 'https://www.africanews.com/feed/rss', 3, TRUE, 'always_on', 'https://www.africanews.com/feed/rss', 'www.africanews.com', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('Middle East Eye', 'Świat / Geopolityka / Bliski Wschód', 'https://www.middleeasteye.net/rss', 3, TRUE, 'always_on', 'https://www.middleeasteye.net/rss', 'www.middleeasteye.net', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('Bellingcat', 'Świat / Geopolityka / Śledztwa OSINT', 'https://www.bellingcat.com/feed/', 4, TRUE, 'always_on', 'https://www.bellingcat.com/feed/', 'www.bellingcat.com', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('The Conversation Global', 'Świat / Geopolityka / Analizy akademickie', 'https://theconversation.com/global/articles.atom', 3, TRUE, 'always_on', 'https://theconversation.com/global/articles.atom', 'theconversation.com', 'atom', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('OSW', 'Polska / Geopolityka / Europa Wschodnia', 'https://www.osw.waw.pl/en/rss.xml', 5, TRUE, 'always_on', 'https://www.osw.waw.pl/en/rss.xml', 'www.osw.waw.pl', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('Atlantic Council', 'Świat / Geopolityka / Analizy transatlantyckie', 'https://www.atlanticcouncil.org/feed/', 4, TRUE, 'always_on', 'https://www.atlanticcouncil.org/feed/', 'www.atlanticcouncil.org', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('Lowy Institute Interpreter', 'Świat / Geopolityka / Azja i Pacyfik', 'https://www.lowyinstitute.org/the-interpreter/rss.xml', 4, TRUE, 'always_on', 'https://www.lowyinstitute.org/the-interpreter/rss.xml', 'www.lowyinstitute.org', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('Breaking Defense', 'Świat / Geopolityka / Obronność', 'https://breakingdefense.com/feed/', 3, TRUE, 'always_on', 'https://breakingdefense.com/feed/', 'breakingdefense.com', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('Defense News', 'Świat / Geopolityka / Obronność', 'https://www.defensenews.com/arc/outboundfeeds/rss/?outputType=xml', 3, TRUE, 'always_on', 'https://www.defensenews.com/arc/outboundfeeds/rss/?outputType=xml', 'www.defensenews.com', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('Channel News Asia', 'Świat / Geopolityka / Azja i Pacyfik', 'https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6511', 4, TRUE, 'always_on', 'https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6511', 'www.channelnewsasia.com', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('VOA World', 'Świat / Geopolityka', 'https://www.voanews.com/api/zq$omekvi_', 3, TRUE, 'always_on', 'https://www.voanews.com/api/zq$omekvi_', 'www.voanews.com', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('Times of Israel', 'Świat / Geopolityka / Bliski Wschód', 'https://www.timesofisrael.com/feed/', 3, TRUE, 'always_on', 'https://www.timesofisrael.com/feed/', 'www.timesofisrael.com', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('BIS Press Releases', 'Świat / Biznes / Banki centralne', 'https://www.bis.org/doclist/all_pressrels.rss', 4, TRUE, 'always_on', 'https://www.bis.org/doclist/all_pressrels.rss', 'www.bis.org', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('Bank of England News', 'Świat / Biznes / Bank centralny', 'https://www.bankofengland.co.uk/rss/news', 3, TRUE, 'always_on', 'https://www.bankofengland.co.uk/rss/news', 'www.bankofengland.co.uk', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('WTO News', 'Świat / Biznes / Handel międzynarodowy', 'https://www.wto.org/library/rss/latest_news_e.xml', 4, TRUE, 'always_on', 'https://www.wto.org/library/rss/latest_news_e.xml', 'www.wto.org', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('Bank of Canada', 'Świat / Biznes / Bank centralny', 'https://www.bankofcanada.ca/feed/', 3, TRUE, 'always_on', 'https://www.bankofcanada.ca/feed/', 'www.bankofcanada.ca', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('Bank of Japan', 'Świat / Biznes / Bank centralny / Azja', 'https://www.boj.or.jp/en/rss/whatsnew.xml', 3, TRUE, 'always_on', 'https://www.boj.or.jp/en/rss/whatsnew.xml', 'www.boj.or.jp', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('FRED Blog', 'Świat / Biznes / Makro i dane', 'https://fredblog.stlouisfed.org/feed/', 3, TRUE, 'always_on', 'https://fredblog.stlouisfed.org/feed/', 'fredblog.stlouisfed.org', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('Liberty Street Economics', 'Świat / Biznes / Makro i rynki', 'https://libertystreeteconomics.newyorkfed.org/feed/', 3, TRUE, 'always_on', 'https://libertystreeteconomics.newyorkfed.org/feed/', 'libertystreeteconomics.newyorkfed.org', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('Bruegel', 'Świat / Biznes / Europa i makro', 'https://www.bruegel.org/rss.xml', 4, TRUE, 'always_on', 'https://www.bruegel.org/rss.xml', 'www.bruegel.org', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb),
  ('WHO News', 'Świat / Geopolityka / Health', 'https://www.who.int/rss-feeds/news-english.xml', 2, TRUE, 'always_on', 'https://www.who.int/rss-feeds/news-english.xml', 'www.who.int', 'rss', 'en', 'valid', NOW(), '{"sourcePortfolio":"curated-geopolitics-business-v2"}'::jsonb)
ON CONFLICT (feed_url) DO UPDATE
SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  priority = EXCLUDED.priority,
  enabled = TRUE,
  selection_mode = 'always_on',
  normalized_feed_url = EXCLUDED.normalized_feed_url,
  canonical_host = EXCLUDED.canonical_host,
  feed_type = EXCLUDED.feed_type,
  language = EXCLUDED.language,
  validation_status = EXCLUDED.validation_status,
  last_validated_at = EXCLUDED.last_validated_at,
  validation_diagnostics = EXCLUDED.validation_diagnostics;
