export const USER_AGENT = "daily-news-digest/4.0 (+vercel-next)";
export const FEED_FETCH_TIMEOUT_MS = 15_000;
export const ARTICLE_FETCH_TIMEOUT_MS = 12_000;
export const ENRICH_TOP_N = 40;
export const ENRICHMENT_BATCH_SIZE = 4;
export const PUBLISH_TOP_N = 30;
export const SUPABASE_FILTER_BATCH_MAX_COUNT = 40;
export const SUPABASE_FILTER_BATCH_MAX_ENCODED_LENGTH = 6_000;
export const SUPABASE_WRITE_BATCH_SIZE = 500;

export const IMPORTANT_KEYWORDS = [
  "breach",
  "exploit",
  "vulnerability",
  "ransomware",
  "attack",
  "zero-day",
  "outage",
  "incident",
  "earnings",
  "ipo",
  "acquisition",
  "merger",
  "sanction",
  "inflation",
  "gdp",
  "layoffs",
  "funding",
  "tariff",
  "rate cut",
  "antitrust",
  "chip",
  "semiconductor",
  "cloud",
  "datacenter",
  "ai",
  "model",
  "launch",
  "security",
  "cyber",
];

export const HIGH_PRIORITY_ENTITIES = [
  "openai",
  "anthropic",
  "deepmind",
  "google",
  "microsoft",
  "nvidia",
  "amd",
  "tsmc",
  "asml",
  "intel",
  "arm",
  "github",
  "cloudflare",
  "vercel",
  "aws",
  "amazon web services",
  "azure",
  "google cloud",
  "meta",
  "apple",
  "cisa",
  "sec",
  "federal reserve",
  "fed",
  "ecb",
  "china",
  "taiwan",
  "russia",
  "ukraine",
  "nato",
];

export const BUILD_RELEVANCE_KEYWORDS = [
  "agent",
  "agents",
  "ai agent",
  "llm",
  "large language model",
  "model release",
  "api",
  "sdk",
  "developer",
  "developers",
  "devtool",
  "devtools",
  "github",
  "framework",
  "open source",
  "cloud",
  "edge",
  "infrastructure",
  "database",
  "serverless",
  "observability",
  "workflow",
  "automation",
  "security",
  "zero-day",
  "vulnerability",
  "exploit",
  "ransomware",
  "breach",
];

export const ACTIONABILITY_KEYWORDS = [
  "api",
  "sdk",
  "release",
  "launch",
  "preview",
  "beta",
  "open source",
  "github",
  "pricing",
  "funding",
  "acquisition",
  "earnings",
  "partnership",
  "integration",
  "developer",
  "migration",
  "patch",
  "update",
  "advisory",
  "cve",
  "zero-day",
  "breach",
  "outage",
  "incident",
  "sanction",
  "sanctions",
  "export control",
  "export controls",
  "tariff",
  "rates",
  "fed",
  "ecb",
];

export const SCOPE_KEYWORDS = [
  "ai",
  "agent",
  "agents",
  "ai agent",
  "llm",
  "large language model",
  "model",
  "model release",
  "foundation model",
  "inference",
  "embedding",
  "openai",
  "anthropic",
  "deepmind",
  "nvidia",
  "gpu",
  "github",
  "developer",
  "developers",
  "devtool",
  "devtools",
  "developer tools",
  "software",
  "engineering",
  "api",
  "apis",
  "sdk",
  "cloudflare",
  "vercel",
  "security",
  "cyber",
  "cybersecurity",
  "zero-day",
  "ransomware",
  "breach",
  "exploit",
  "vulnerability",
  "economy",
  "market",
  "markets",
  "business",
  "startup",
  "startups",
  "funding",
  "ipo",
  "acquisition",
  "earnings",
  "valuation",
  "venture",
  "saas",
  "inflation",
  "gdp",
  "fed",
  "ecb",
  "rates",
  "sanctions",
  "export controls",
  "tariff",
  "chip",
  "chips",
  "semiconductor",
  "taiwan",
  "china",
  "energy",
  "cloud",
  "cloud infrastructure",
  "datacenter",
  "data center",
  "serverless",
  "edge",
  "database",
  "observability",
];
